# Generated by Django 6.0 on 2025-12-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upskill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='upskill.module'),
        ),
        migrations.AddField(
            model_name='image',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='upskill.module'),
        ),
        migrations.AddField(
            model_name='text',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='upskill.module'),
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='upskill.module'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=2, upload_to='videos/', verbose_name='Video File'),
            preserve_default=False,
        ),
    ]
